version: 2.1

orbs:
  node: circleci/node@6.1.0

jobs:
  smoke-tests:
    docker:
      - image: cimg/node:22.0-browsers
    steps:
      - checkout
      
      - node/install-packages:
          pkg-manager: npm
      
      - run:
          name: Install Microsoft Edge
          command: |
            curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
            sudo install -o root -g root -m 644 microsoft.gpg /etc/apt/trusted.gpg.d/
            sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/edge stable main" > /etc/apt/sources.list.d/microsoft-edge-dev.list'
            sudo rm microsoft.gpg
            sudo apt update
            sudo apt install microsoft-edge-stable
      
      - run:
          name: Run smoke tests
          command: npx cypress run --spec cypress/tests/e2e/heroku-app-smoke.cy.js
      
      - store_artifacts:
          path: cypress/cypress-reports/
          destination: cypress-report

workflows:
  smoke-tests:
    jobs:
      - smoke-tests
  
  nightly-smoke-tests:
    triggers:
      - schedule:
          cron: "0 3 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - smoke-tests
